services:
  csvserver:
    image: infracloudio/csvserver
    container_name: csvserver
    ports:
      - "9393:9300"
    volumes:
      - ./inputFile:/csvserver/inputdata
    env_file:
      - ./csvserver.env
